### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by KokoseiJ** [KokoseiJ/NicoBot#1]
- [x] Change default value of API calls to an object that states EMPTY, and use a function that remove parameters with it from the postdata.
- [x] Refactor SelectableEvent to Event object to support Windows- which doesn't support selecting non-socket fd.
- [x] Unify `putdata`, `getdata`, `patchdata` to `postdata`
- [x] Implement Rate limit handler
- [x] add private send_request method to each client to eliminate the unnecessary multiple usage of f-strings in API request.
- [x] Implement handler
- [x] Implement AudioPlayer, AudioSource class
- [x] Write docstring to necessary components
- [x] Add File object to centralize the way of handling files in HTTP API request
- [x] Refactor Guild event handling part
- [x] Add embed 
- [x] Refactor methods to accept embed object
- [x] properly fix heartbeat thread
- [x] Rewrite Rate limit handler to prevent 429
- [x] Support slash command
- [ ] Separate the repo from NicoBot
- [ ] Make Docs

==================== Beta release ====================

- [ ] Implement resuming for voice clients
- [ ] Write tests ffs
- [ ] Change type handling to enum
- [ ] Add support to chat threads?
